# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce2112cc6e890799436d54dccf04aad2f027d9825f3c1feef9ffc106ab3faa8adf6cbf83b7dc1a65cc45ea47f8a0b3b85b1e1d1cd245806c3e0bb69151c278e5

test:
  secret_key_base: f499e7b26e1eb9cea24712a7babee3a5a0b2df68d25b16793b58c0079b8ea5bcaee7c2b3100172a26018c518e856451b175b706cb15e9bc41e48ad68429f86d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
